### ISSUE TITLE
Huge memory usage

### ISSUE THREAD

**Issue by DevataDev** [monyone/biim#2]
Hi @monyone 
Thank you for this awesome works, i have been test this, and try to run 1 hours live stream and it's ends up with memory usage spiking to 15 GB. Seems the segment is still being hold even not used anymore.

Is there any guidance on this ?

Thank you

**Comment by monyone** [comment]
@DevataDev Thanks for feedback!

`'-l', '--list_size'` not specified, biim generate infinity m3u8 and hold infinite segments.
In most case, specify 3 or 4.  (For ordinaly HLS compatibility)

**Comment by monyone** [comment]
@DevataDev I fix CPU usage for H264 keyframe parsing.
It seems to total CPU usage reduced by half.

But, python still high CPU usage...

If you use high bitrate mpegts stream, please reduce bitrate, or use other implemetation.
(For example, [My node.js LL-HLS implementation](https://github.com/monyone/node-llhls-origin-example) is x5 faster and reduce CPU usage than this python version. )
