### ISSUE TITLE
Problem start

### ISSUE THREAD

**Issue by Gurman520** [monyone/biim#3]
Hello. 
I wanted to use your project, but I had a problem. I don't fully understand what type of file should be specified instead of "xxx". I also get an error and an exception when launching your application. 
I really hope for your help.
![image](https://user-images.githubusercontent.com/78251000/206098318-babb8f66-d7f8-4840-8acc-8467e9699430.png)

**Comment by monyone** [comment]
@Gurman520 
Sorry for inconvenience, windows seems not support read stdin by asyncio.
Please use other Environment.

Typicall ffmpeg parameter (from mpegts over rtp) is below.
```bash
ffmpeg -i -f rtp_mpegts rtp://localhost:5678 -c:v copy -c:a copy -f mpegts -
```
Other ffmpeg live input are also accepted.

**Comment by bikideka321** [comment]
Hey would anyone explain little more what type of file should be inplace of "xxx" in this command

**Comment by monyone** [comment]
@Gurman520 @bikideka321 
Sorry for late. Windows Support currently avaiable!
And, Sample (Test Pattern) Injesting to biim example write in README.

Thanks.
